Apply AIX xlC13 fix (already in OpenJ9)
AdoptOpenJDK/openjdk-jdk11 pull request #1
Opened 2018-09-24 10:47 UTC by sxa555

Hopefully resolves https://github.com/AdoptOpenJDK/openjdk-build/issues/456 (applies the patch from //patch-diff.githubusercontent.com/raw/ibmruntimes/openj9-openjdk-jdk11/pull/15.patch

2018-09-24 10:50 UTC, karianna requested changes
revert copyright header

2018-09-24 11:02 UTC, sxa555 commented
@keith-ca Are you ok with me putting this patch into the adoptopenjdk/hotpost builds? And do you know if this has been reported upstream with the openjdk project yet?

2018-09-27 14:06 UTC, keithc-ca commented
Yes, the plan is to propose [12] (a copy of [11]) to openjdk, but that process hasn't started yet.
I don't see any problem with this which just gets a head start.

[11] https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/15
[12] https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/27

2018-09-27 14:21 UTC, karianna commented
Cool - @sxa555 LMK when you've got a signed commit version of this and we'll patch.

2018-09-27 14:57 UTC, sxa555 commented
Should be good @karianna

2018-09-27 15:07 UTC, karianna approved these changes
LGTM - this was tested on an internal Adopt System and 'official' patch will be backported from 12

2018-09-27 15:07 UTC, merged